[package]
name = "wakfu_png"
version = "1.3.0"
edition = "2021"

[dependencies]
anyhow = "1"
pico-args = "0.4"
byte = "0.2"
modular-bitfield = "0.11"
glam = "0.20"
itertools = "0.10"
image = "0.24.3"
bytebuffer-rs = "0.4.0"
imageproc = "0.23.0"
rand = "0.8.5"
xml-rs = "0.8.4"

[dependencies.zip]
version = "0.6"
default-features = false
features = [ "deflate" ]

[dependencies.num-traits]
version = "0.2.0"

[profile.dev.package.image]
opt-level = 3
